
services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    networks:
      - network1
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=memoiruser
      - DB_PASSWORD=Informatique_2022
      - DB_NAME=memoir

  frontend:
    build: ./try
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - network1

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Informatique_2022
      MYSQL_DATABASE: memoir
      MYSQL_USER: memoiruser
      MYSQL_PASSWORD: Informatique_2022
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - network1
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - network1
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Informatique_2022

volumes:
  mysql_data:

networks:
  network1:
    driver: bridge
